spring:
  ldap:
    urls: ldap://localhost:389
    base: dc=mycompany,dc=com
    username: cn=admin,dc=mycompany,dc=com
    password: admin

server:
  port: 8081

jwt:
  secret: MyJWTSecretKeyThatShouldBeSecure
  expirationMs: 120000            # 2 mins access token
  refreshExpirationMs: 86400000   # 1 day